### ISSUE TITLE
Document HotswapAgent core vs fatjar

### ISSUE THREAD

**Issue by cdalexndr** [TravaOpenJDK/trava-jdk-11-dcevm#31]
What's the difference between `-XX:HotswapAgent=core` and `-XX:HotswapAgent=fatjar`?

**Comment by skybber** [comment]
HotswapAgent core has no plugin except core JVM plugins. Then it is faster since less scanning tasks are necessary to be done, less class copying to target classloaders, there is no need to disable plugins. You choose only what you want. If you use ha-core, then plugins must be configured as maven dependecies in pom.xml

**Comment by cdalexndr** [comment]
Please add to https://github.com/TravaOpenJDK/trava-jdk-11-dcevm/blob/master/README.md

**Comment by skybber** [comment]
Done
