### ISSUE TITLE
Not notarized on macOS

### ISSUE THREAD

**Issue by brendan-lee** [TravaOpenJDK/trava-jdk-11-dcevm#45]
Every .dylib file reports the same warning "cannot be opened because the developer cannot be verified" on Big Sur and I have to click "Allow Anyway" for every single file, which is really inconvenient.

Any solutions?

<img width="260" alt="image" src="https://user-images.githubusercontent.com/10712544/117463625-76486f80-af82-11eb-9136-fc8936b5aae2.png">

<img width="577" alt="image" src="https://user-images.githubusercontent.com/10712544/117464768-90cf1880-af83-11eb-99d2-250a81d2477b.png">

**Comment by brendan-lee** [comment]
I'll take a look at it, thank you @skybber 👍

**Comment by weltonrodrigo** [comment]
Workaround is to

```
xattr -d com.apple.quarantine ~/Downloads/dcevm-11.0.11+1/
```

Where `~/Downloads/dcevm-11.0.11+1/` is the place where DCEVM is uncompressed.

**Comment by brendan-lee** [comment]
> Workaround is to
> 
> ```
> xattr -d com.apple.quarantine ~/Downloads/dcevm-11.0.11+1/
> ```
> 
> Where `~/Downloads/dcevm-11.0.11+1/` is the place where DCEVM is uncompressed.

It works, really appreciate it! @weltonrodrigo

**Comment by pgerhard** [comment]
@brendan-lee I had lots of issues using the DCEVM image on MacOS. These were caused by the folder contents not being notarized, however on macOS Catalina when selecting "Allow anyway" the folder is opened but it does not solve the issue.
I'd suggest adding the above command line command `xattr -d com.apple.quarantine ~/Downloads/dcevm-11.0.11+1/
` to the installation instructions for MacOS. What are your thoughts on this?

**Comment by brendan-lee** [comment]
Great idea, it would be helpful for others who face the same problem 👍
