### ISSUE TITLE
Help with NetBeans 12.5

### ISSUE THREAD

**Issue by stefanos82** [TravaOpenJDK/trava-jdk-11-dcevm#53]
With the latest NetBeans 12.5 and openjdk-11-jre-dcevm on my Debian testing 64-bit I cannot use it anymore.

Previously with openjdk-8-jre-dcevm worked just fine; now I don't know what happened and it's not working.

Can anyone point me at the right direction with instructions please?

**Comment by kerdosmedia** [comment]
I am still trying to get this working completely myself. I see this is older so if you have any new information please post it. I'm using netbeans 13 and openjdk-11-jre-dcevm

The big difference is between hotswapagent being integrated into 11 and not 8. You don't have to include the old compiler arguments -XXaltjvn and -javaagent. Instead you would just use -XX:HotswapAgent=fatjar see https://github.com/HotswapProjects/HotswapAgent

see http://hotswapagent.org/mydoc_setup_netbeans.html for where those changes need to be made but remember to use fatjar instead of what's in the instructions if you're using 11.

**Comment by stefanos82** [comment]
I don't use it anymore, because I replaced it with `openjdk-17` which compiles instantly in my case.

I don't know whether they have bundled it in `openjdk` now, but it works extremely fast.

**Comment by kerdosmedia** [comment]
I just tried to install jetbrains [Release 17.0.2-b396.4](https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jbr17.0.2b396.4) to see if it will fix my issues but now I can't start netbeans with that as my JRE I get jdk.jshell not found when trying to launch netbeans. what version of openjdk 17 are you using please?

**Comment by stefanos82** [comment]
Uninstall this custom runtime and NetBeans should work; why would you use this one that is for IntelliJ platform-based applications?

I use `17.0.2+8-1` on Debian testing 64-bit.

**Comment by kerdosmedia** [comment]
I'm following these instructions that say to use the jetbrains jdk http://hotswapagent.org/mydoc_quickstart-jdk17.html

Can you please give me detailed instructions on how you setup netbeans with jdk 17 and hotswapagent? I had 11 running but kept getting errors on hibernate so trying 17 and stuck again.

Geia

**Comment by stefanos82** [comment]
> I'm following these instructions that say to use the jetbrains jdk http://hotswapagent.org/mydoc_quickstart-jdk17.html
> 
> Can you please give me detailed instructions on how you setup netbeans with jdk 17 and hotswapagent? I had 11 running but kept getting errors on hibernate so trying 17 and stuck again.
> 

Oh I haven't done anything with hotswapagent; all I did was to first install `openjdk-17` and test it with NetBeans and immediately blew my mind with its instant compilation procedure.

Of course after this, I uninstalled `openjdk-11`.

Does this help somehow?
